export const ADD_PASSENGER = "ADD_PASSENGER";
export const ADD_TO_PAX_SEATMAP = 'ADD_TO_PAX_SEATMAP';
export const UPDATE_PAX_SEATMAP = 'UPDATE_PAX_SEATMAP';
export const REMOVE_FROM_PAX_SEATMAP = 'REMOVE_FROM_PAX_SEATMAP';
export const CLEAR_PAX_SEATMAP = 'CLEAR_PAX_SEATMAP';